import api from "@utils/api";
import type {
  Collection,
  DailyCollectionGroup,
  CreateCollectionData,
  UpdateCollectionData,
  PaymentUpdateData,
  CollectionStats,
  AutoGenerateData,
  MemberWithLoans,
} from "./types";
import type { Repayment } from "@features/repayments/types";

export type CollectionsQuery = {
  page?: number;
  limit?: number;
  centerId?: string;
  memberId?: string;
  startDate?: string;
  endDate?: string;
  search?: string;
  sortBy?: string;
  sortOrder?: "ASC" | "DESC";
};

export type PaginatedCollections = {
  items: Collection[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
};

// Helper function to clean query parameters
const cleanQuery = (query: CollectionsQuery): CollectionsQuery => {
  const cleaned: Record<string, unknown> = {};

  Object.entries(query).forEach(([key, value]) => {
    if (value !== undefined && value !== null && value !== "") {
      // For search, ensure minimum length
      if (key === "search" && typeof value === "string") {
        const trimmed = value.trim();
        if (trimmed.length >= 2) {
          cleaned[key] = trimmed;
        }
      } else {
        cleaned[key] = value;
      }
    }
  });

  return cleaned as CollectionsQuery;
};

export const collectionsService = {
  // Get all collections (paginated)
  getAllCollections: async (
    query: CollectionsQuery = {},
  ): Promise<PaginatedCollections> => {
    const cleanedQuery = cleanQuery(query);
    console.log("Making API request with cleaned query:", cleanedQuery);

    const response = await api.get("/collection", { params: cleanedQuery });
    return response.data;
  },

  // Get collection by ID
  getCollectionById: async (id: string): Promise<Collection> => {
    const response = await api.get(`/collection/${id}`);
    return response.data;
  },

  // Get today's collections
  getTodayCollections: async (
    date?: string,
    signal?: AbortSignal,
  ): Promise<DailyCollectionGroup[]> => {
    const response = await api.get("/collection/daily", {
      params: date ? { date } : undefined,
      signal,
    });
    return response.data;
  },

  // Get all collections grouped by center/date
  getAllCollectionGroups: async (
    date?: string,
    signal?: AbortSignal,
  ): Promise<DailyCollectionGroup[]> => {
    const response = await api.get("/collection/grouped", {
      params: date ? { date } : undefined,
      signal,
    });
    return response.data;
  },

  // Get collections by date
  getCollectionsByDate: async (date: string): Promise<Collection[]> => {
    const response = await api.get(`/collection/date/${date}`);
    return response.data;
  },

  // Get collections for a specific center on a specific date
  getCenterCollectionsByDate: async (
    centerId: string,
    date: string,
    signal?: AbortSignal,
  ): Promise<Collection[]> => {
    const response = await api.get(
      `/collection/center/${centerId}/date/${date}`,
      { signal },
    );
    return response.data;
  },

  // Get center members with loan information
  getCenterMembers: async (
    centerId: string,
    date?: string,
    signal?: AbortSignal,
  ): Promise<MemberWithLoans[]> => {
    const response = await api.get(`/members/center/${centerId}`, {
      params: date ? { date } : undefined,
      signal,
    });
    return response.data;
  },

  // Create new collection
  createCollection: async (data: CreateCollectionData): Promise<Collection> => {
    const response = await api.post("/collection", data);
    return response.data;
  },

  // Update collection
  updateCollection: async (
    id: string,
    data: UpdateCollectionData,
  ): Promise<Collection> => {
    const response = await api.patch(`/collection/${id}`, data);
    return response.data;
  },

  // Update collection payment
  updatePayment: async (
    id: string,
    data: PaymentUpdateData,
  ): Promise<Collection> => {
    const response = await api.patch(`/collection/${id}/payment`, data);
    return response.data;
  },

  // Delete collection
  deleteCollection: async (id: string): Promise<{ deleted: boolean }> => {
    const response = await api.delete(`/collection/${id}`);
    return response.data;
  },

  // Auto-generate collections for a center and date
  autoGenerateCollections: async (
    data: AutoGenerateData,
  ): Promise<Collection[]> => {
    const response = await api.post("/collection/auto-generate", data);
    return response.data;
  },

  // Get collection statistics
  getCollectionStats: async (
    startDate: string,
    endDate: string,
  ): Promise<CollectionStats> => {
    const response = await api.get(
      `/collection/stats?startDate=${startDate}&endDate=${endDate}`,
    );
    return response.data;
  },

  // Create repayment
  createRepayment: async (data: {
    loanId: string;
    memberId: string;
    centerId: string;
    amount: number;
    collectionDate?: string;
    notes?: string;
    useSavings?: boolean;
  }): Promise<Repayment> => {
    const response = await api.post("/repayments", data);
    return response.data;
  },

  getPendingRepaymentsForCollection: async (
    centerId: string,
    collectionDate: string,
    signal?: AbortSignal,
  ): Promise<Repayment[]> => {
    const response = await api.get(
      `/repayments/pending/collections/${centerId}/${collectionDate}/repayments`,
      { signal },
    );
    return response.data;
  },
};

export default collectionsService;

export const loansClient = {
  checkEligibilityByLoan: async (loanId: string) => {
    const res = await api.get(`/loans/${loanId}/eligibility`);
    return res.data;
  },
  reloan: async (
    loanId: string,
    body: {
      newPrincipalAmount: number;
      newTermWeeks: 4 | 8 | 12 | 24;
      monthlyInterestRate?: number;
      mode: "payoff" | "netoff";
      serviceCharge?: number;
      notarialFee?: number;
      savings?: number;
    },
  ) => {
    const res = await api.post(`/loans/${loanId}/reloan`, body);
    return res.data;
  },
};
