import axios from "axios";
import api from "../../utils/api";
import type {
  Collection,
  DailyCollectionGroup,
  CreateCollectionData,
  UpdateCollectionData,
  PaymentUpdateData,
  CollectionStats,
  AutoGenerateData,
  MemberWithLoans,
} from "./types";
import type { Repayment } from "@features/repayments/types";
import { useAuthStore } from "@features/auth/authStore";

const API_BASE_URL =
  import.meta.env.VITE_API_URL || "http://localhost:3000/api";

const collectionsApi = axios.create({
  baseURL: `${API_BASE_URL}/collection`,
  headers: {
    "Content-Type": "application/json",
  },
});

// Add token to requests if available
collectionsApi.interceptors.request.use((config) => {
  const token = useAuthStore.getState().token;
  if (token) {
    config.headers = config.headers ?? {};
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

// Add response interceptor for better error handling
collectionsApi.interceptors.response.use(
  (response) => response,
  (error) => {
    if (error.response?.data?.message) {
      console.error("API Error:", error.response.data.message);
    }
    return Promise.reject(error);
  }
);

export type CollectionsQuery = {
  page?: number;
  limit?: number;
  centerId?: string;
  memberId?: string;
  startDate?: string;
  endDate?: string;
  search?: string;
  sortBy?: string;
  sortOrder?: "ASC" | "DESC";
};

export type PaginatedCollections = {
  items: Collection[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
};

const repaymentsApi = axios.create({
  baseURL: `${API_BASE_URL}/repayments`,
  headers: { "Content-Type": "application/json" },
});

repaymentsApi.interceptors.request.use((config) => {
  const token = useAuthStore.getState().token;
  if (token) {
    config.headers = config.headers ?? {};
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

// Helper function to clean query parameters
const cleanQuery = (query: CollectionsQuery): CollectionsQuery => {
  const cleaned: Record<string, unknown> = {};

  Object.entries(query).forEach(([key, value]) => {
    if (value !== undefined && value !== null && value !== "") {
      // For search, ensure minimum length
      if (key === "search" && typeof value === "string") {
        const trimmed = value.trim();
        if (trimmed.length >= 2) {
          cleaned[key] = trimmed;
        }
      } else {
        cleaned[key] = value;
      }
    }
  });

  return cleaned as CollectionsQuery;
};

export const collectionsService = {
  // Get all collections (paginated)
  getAllCollections: async (
    query: CollectionsQuery = {}
  ): Promise<PaginatedCollections> => {
    const cleanedQuery = cleanQuery(query);
    console.log("Making API request with cleaned query:", cleanedQuery);

    const response = await collectionsApi.get("/", { params: cleanedQuery });
    return response.data;
  },

  // Get collection by ID
  getCollectionById: async (id: string): Promise<Collection> => {
    const response = await collectionsApi.get(`/${id}`);
    return response.data;
  },

  // Get today's collections
  getTodayCollections: async (
    date?: string
  ): Promise<DailyCollectionGroup[]> => {
    const response = await collectionsApi.get("/daily", {
      params: date ? { date } : undefined,
    });
    return response.data;
  },

  // Get all collections grouped by center/date
  getAllCollectionGroups: async (date?: string): Promise<DailyCollectionGroup[]> => {
    const response = await collectionsApi.get("/grouped", {
      params: date ? { date } : undefined,
    });
    return response.data;
  },

  // Get collections by date
  getCollectionsByDate: async (date: string): Promise<Collection[]> => {
    const response = await collectionsApi.get(`/date/${date}`);
    return response.data;
  },

  // Get collections for a specific center on a specific date
  getCenterCollectionsByDate: async (
    centerId: string,
    date: string
  ): Promise<Collection[]> => {
    const response = await collectionsApi.get(
      `/center/${centerId}/date/${date}`
    );
    return response.data;
  },

  // Get center members with loan information
  getCenterMembers: async (centerId: string): Promise<MemberWithLoans[]> => {
    const response = await api.get(`/members/center/${centerId}`);
    return response.data;
  },

  // Create new collection
  createCollection: async (data: CreateCollectionData): Promise<Collection> => {
    const response = await collectionsApi.post("/", data);
    return response.data;
  },

  // Update collection
  updateCollection: async (
    id: string,
    data: UpdateCollectionData
  ): Promise<Collection> => {
    const response = await collectionsApi.patch(`/${id}`, data);
    return response.data;
  },

  // Update collection payment
  updatePayment: async (
    id: string,
    data: PaymentUpdateData
  ): Promise<Collection> => {
    const response = await collectionsApi.patch(`/${id}/payment`, data);
    return response.data;
  },

  // Delete collection
  deleteCollection: async (id: string): Promise<{ deleted: boolean }> => {
    const response = await collectionsApi.delete(`/${id}`);
    return response.data;
  },

  // Auto-generate collections for a center and date
  autoGenerateCollections: async (
    data: AutoGenerateData
  ): Promise<Collection[]> => {
    const response = await collectionsApi.post("/auto-generate", data);
    return response.data;
  },

  // Get collection statistics
  getCollectionStats: async (
    startDate: string,
    endDate: string
  ): Promise<CollectionStats> => {
    const response = await collectionsApi.get(
      `/stats?startDate=${startDate}&endDate=${endDate}`
    );
    return response.data;
  },

  // Create repayment
  createRepayment: async (data: {
    loanId: string;
    memberId: string;
    centerId: string;
    amount: number;
    collectionDate?: string;
    notes?: string;
    useSavings?: boolean;
  }): Promise<Repayment> => {
    const response = await repaymentsApi.post("/", data);
    return response.data;
  },

  getPendingRepaymentsForCollection: async (
    centerId: string,
    collectionDate: string
  ): Promise<Repayment[]> => {
    const response = await repaymentsApi.get(
      `/pending/collections/${centerId}/${collectionDate}/repayments`
    );
    return response.data;
  },
};

export default collectionsService;

// Loans-related lightweight APIs for reloan/eligibility
const loansApi = axios.create({
  baseURL: `${API_BASE_URL}/loans`,
  headers: { "Content-Type": "application/json" },
});

loansApi.interceptors.request.use((config) => {
  const token = useAuthStore.getState().token;
  if (token) {
    config.headers = config.headers || {};
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

export const loansClient = {
  checkEligibilityByLoan: async (loanId: string) => {
    const res = await loansApi.get(`/${loanId}/eligibility`);
    return res.data;
  },
  reloan: async (
    loanId: string,
    body: {
      newPrincipalAmount: number;
      newTermWeeks: 4 | 8 | 12;
      mode: "payoff" | "netoff";
      serviceCharge?: number;
    }
  ) => {
    const res = await loansApi.post(`/${loanId}/reloan`, body);
    return res.data;
  },
};
