export interface Collection {
  id: string;
  collectionDate: string;
  amount: number;
  netRelease: number;
  paymentReceived: number;
  notes?: string;
  isAutoGenerated: boolean;
  centerId: string;
  memberId: string;
  center?: Center;
  member?: Member;
  createdAt: string;
  updatedAt: string;
}

export interface Center {
  id: string;
  name: string;
  collectionDay: string;
  address?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Member {
  id: string;
  firstName: string;
  lastName: string;
  middleName: string;
  contactNumber: string;
  address: string;
  birthDate?: string;
  center?: Center;
  createdAt: string;
  updatedAt: string;
}

export interface DailyCollectionGroup {
  centerId: string;
  centerName: string;
  collectionDay: string;
  collectionDate: string;
  totalMembers: number;
  collections: Collection[];
  pendingCollections: number;
  totalAmount: number;
  totalReceived: number;
}

export interface CreateCollectionData {
  collectionDate: string;
  amount: number;
  netRelease?: number;
  paymentReceived?: number;
  notes?: string;
  isAutoGenerated?: boolean;
  centerId: string;
  memberId: string;
}

export interface UpdateCollectionData {
  collectionDate?: string;
  amount?: number;
  netRelease?: number;
  paymentReceived?: number;
  notes?: string;
  isAutoGenerated?: boolean;
}

export interface PaymentUpdateData {
  paymentAmount: number;
  notes?: string;
}

export interface CollectionFormData {
  memberId: string;
  centerId: string;
  amount: number;
  paymentReceived: number;
  collectionDate: string;
  notes?: string;
}

export interface CollectionStats {
  totalCollections: number;
  totalAmount: number;
  totalReceived: number;
  pendingAmount: number;
  paidCollections: number;
  pendingCollections: number;
}

export interface AutoGenerateData {
  centerId: string;
  date: string;
}
