export interface Member {
  id: string;
  firstName: string;
  lastName: string;
  middleName: string;
  contactNumber: string;
  address: string;
  birthDate?: string;
  center?: Center;
  createdAt: string;
  updatedAt: string;
}

export interface MemberWithLoans extends Member {
  loans: Array<{
    id: string;
    amount: number;
    balance: number;
    status: string;
    dueDate: string;
    loanCreatedDate?: string;
    createdAt?: string;
    netCashReleased?: number;
    paymentCountDisplayOffset?: number;
  }>;
  totalLoanAmount: number;
  totalBalance: number;
  overallAmount?: number;
  weeklyPaymentAmount?: number;
  totalTermWeeks?: number;
  totalSavings?: number;
  netCashReleased?: number;
  netCashReleasedForDate?: number;
  numberOfPayments?: number;
  collection?: Collection;
}

export interface Center {
  id: string;
  name: string;
  collectionDay: string;
  address?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Collection {
  id: string;
  memberId: string;
  centerId: string;
  amount: number;
  netRelease: number;
  paymentReceived: number;
  collectionDate: string;
  notes?: string;
  isAutoGenerated: boolean;
  numberOfPayments?: number;
  advancePaymentAmount?: number;
  advancePaymentStatus?: "none" | "partial" | "full";
  member?: Member;
  center?: Center;
  createdAt: string;
  updatedAt: string;
}

export interface DailyCollectionGroup {
  centerId: string;
  centerName: string;
  collectionDay: string;
  collectionDate: string;
  totalAmount: number;
  totalReceived: number;
  totalMembers: number;
  pendingCollections: number;
  collections: Collection[];
}

export interface CollectionFormData {
  memberId: string;
  centerId: string;
  amount: number;
  paymentReceived: number;
  collectionDate: string;
  notes?: string;
}

export interface CollectionStats {
  totalCollections: number;
  totalAmount: number;
  totalReceived: number;
  pendingAmount: number;
  paidCollections: number;
  pendingCollections: number;
}

export interface CreateCollectionData {
  collectionDate: string;
  amount: number;
  netRelease?: number;
  paymentReceived?: number;
  notes?: string;
  isAutoGenerated?: boolean;
  centerId: string;
  memberId: string;
}

export interface UpdateCollectionData {
  collectionDate?: string;
  amount?: number;
  netRelease?: number;
  paymentReceived?: number;
  notes?: string;
  isAutoGenerated?: boolean;
}

export interface PaymentUpdateData {
  paymentAmount: number;
  notes?: string;
}

export interface AutoGenerateData {
  centerId: string;
  date: string;
}

export interface CollectionExportBundle {
  group: DailyCollectionGroup;
  members: MemberWithLoans[];
}
