import {
  IsString,
  IsNumber,
  IsOptional,
  IsBoolean,
  IsDateString,
} from 'class-validator';

export class CreateCollectionDto {
  @IsDateString()
  collectionDate: string;

  @IsNumber()
  amount: number;

  @IsNumber()
  @IsOptional()
  netRelease?: number;

  @IsNumber()
  @IsOptional()
  paymentReceived?: number;

  @IsString()
  @IsOptional()
  notes?: string;

  @IsBoolean()
  @IsOptional()
  isAutoGenerated?: boolean;

  @IsString()
  centerId: string;

  @IsString()
  memberId: string;
}
