import {
  IsString,
  IsNumber,
  IsOptional,
  IsBoolean,
  IsDateString,
  IsEnum,
} from 'class-validator';
import { AdvancePaymentStatus } from '../entities/collection.entity';

export class CreateCollectionDto {
  @IsDateString()
  collectionDate: string;

  @IsNumber()
  amount: number;

  @IsNumber()
  @IsOptional()
  netRelease?: number;

  @IsNumber()
  @IsOptional()
  paymentReceived?: number;

  @IsString()
  @IsOptional()
  notes?: string;

  @IsBoolean()
  @IsOptional()
  isAutoGenerated?: boolean;

  @IsNumber()
  @IsOptional()
  numberOfPayments?: number;

  @IsNumber()
  @IsOptional()
  advancePaymentAmount?: number;

  @IsEnum(AdvancePaymentStatus)
  @IsOptional()
  advancePaymentStatus?: AdvancePaymentStatus;

  @IsString()
  centerId: string;

  @IsString()
  memberId: string;
}
