import type { DailyCollectionGroup, MemberWithLoans } from "../types";

// Types for batch export
export type CollectionExportBundle = {
  group: DailyCollectionGroup;
  members: MemberWithLoans[];
};

// Fallback CSV export function
const exportToCSV = (
  collectionGroup: DailyCollectionGroup,
  members: MemberWithLoans[]
): void => {
  try {
    // Create CSV content
    const csvContent = [
      // Summary section
      "Collection Report Summary",
      "",
      "Center Information",
      `Center Name,${collectionGroup.centerName}`,
      `Collection Day,${collectionGroup.collectionDay}`,
      `Collection Date,${collectionGroup.collectionDate}`,
      `Total Members,${collectionGroup.totalMembers}`,
      "",
      "Financial Summary",
      `Total Amount Expected,₱${collectionGroup.totalAmount.toLocaleString()}`,
      `Total Amount Received,₱${(collectionGroup.collections || [])
        .reduce((sum, c: any) => {
          const received = c?.amountReceived ?? c?.paymentReceived ?? 0;
          return sum + (Number(received) || 0);
        }, 0)
        .toLocaleString()}`,
      `Total Remaining Balance,₱${(
        collectionGroup.totalAmount - collectionGroup.totalReceived
      ).toLocaleString()}`,
      `Pending Collections,${collectionGroup.pendingCollections}`,
      "",
      "Status Breakdown",
      `Paid Collections,${
        collectionGroup.collections.filter((c: any) => {
          const received = Number(c?.amountReceived ?? c?.paymentReceived ?? 0);
          return received >= Number(c.amount || 0);
        }).length
      }`,
      `Partial Collections,${
        collectionGroup.collections.filter((c: any) => {
          const received = Number(c?.amountReceived ?? c?.paymentReceived ?? 0);
          return received > 0 && received < Number(c.amount || 0);
        }).length
      }`,
      `Pending Collections,${
        collectionGroup.collections.filter((c: any) => {
          const received = Number(c?.amountReceived ?? c?.paymentReceived ?? 0);
          return received <= 0;
        }).length
      }`,
      "",
      // Members detail section
      "Members Detail",
      "Member Name,Contact Number,Address,Overall Amount,Term Weeks,Net Cash Released,No. of Payments,Savings,Remaining Balance,Weekly Payment,Payment Status,Notes",
      ...members.map((member) =>
        [
          `${member.firstName} ${member.lastName}`,
          member.contactNumber || "-",
          member.address || "-",
          `₱${member.overallAmount?.toLocaleString() || "0"}`,
          member.totalTermWeeks || "-",
          `₱${member.netCashReleased?.toLocaleString() || "0"}`,
          member.numberOfPayments || "0",
          `₱${member.totalSavings?.toLocaleString() || "0"}`,
          `₱${member.totalBalance?.toLocaleString() || "0"}`,
          `₱${member.weeklyPaymentAmount?.toLocaleString() || "0"}`,
          (member.collection?.paymentReceived || 0) >=
          (member.weeklyPaymentAmount || 0)
            ? "PAID"
            : "PENDING",
          member.collection?.notes || "-",
        ].join(",")
      ),
      "",
      // Collections detail section
      "Collections Detail",
      "Member Name,Collection Date,Amount Expected,Amount Received,Balance,Status,Notes,Auto Generated",
      ...collectionGroup.collections.map((collection: any) =>
        [
          `${collection.member?.firstName || ""} ${
            collection.member?.lastName || ""
          }`,
          collection.collectionDate,
          `₱${collection.amount.toLocaleString()}`,
          `₱${(
            Number(
              collection.amountReceived ?? collection.paymentReceived ?? 0
            ) || 0
          ).toLocaleString()}`,
          `₱${(
            Number(collection.amount || 0) -
            (Number(
              collection.amountReceived ?? collection.paymentReceived ?? 0
            ) || 0)
          ).toLocaleString()}`,
          (Number(
            collection.amountReceived ?? collection.paymentReceived ?? 0
          ) || 0) >= Number(collection.amount || 0)
            ? "PAID"
            : (Number(
                collection.amountReceived ?? collection.paymentReceived ?? 0
              ) || 0) > 0
            ? "PARTIAL"
            : "PENDING",
          collection.notes || "-",
          collection.isAutoGenerated ? "Yes" : "No",
        ].join(",")
      ),
    ].join("\n");

    // Create and download file
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);
    link.setAttribute("href", url);
    link.setAttribute(
      "download",
      `Collection_Report_${
        collectionGroup.centerName
      }_${collectionGroup.collectionDate.replace(/-/g, "_")}.csv`
    );
    link.style.visibility = "hidden";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  } catch (error) {
    console.error("CSV export failed:", error);
    throw new Error("Failed to export collection data as CSV.");
  }
};

// Helper: build the single-sheet data structure for a group
const buildGroupSheetData = (
  collectionGroup: DailyCollectionGroup,
  members: MemberWithLoans[]
): {
  data: (string | number)[][];
  merges: { s: { r: number; c: number }; e: { r: number; c: number } }[];
} => {
  const sheetData: (string | number)[][] = [];

  // Helpers to read values regardless of backend field names
  const getMemberReceived = (m: any): number => {
    const fromCollection =
      m?.collection?.amountReceived ?? m?.collection?.paymentReceived;
    if (fromCollection !== undefined) return Number(fromCollection) || 0;
    const activeLoan = (m?.loans || []).find(
      (l: any) => l?.status === "active"
    );
    const amountPaidRaw = activeLoan?.amountPaid;
    if (amountPaidRaw !== undefined) return Number(amountPaidRaw) || 0;
    const weeksPaid = Number(activeLoan?.weeksPaid || 0);
    const weekly = Number(
      m?.weeklyPaymentAmount || activeLoan?.weeklyPaymentAmount || 0
    );
    return weeksPaid * weekly;
  };
  const getMemberWeeksPaid = (m: any): number => {
    const activeLoan = (m?.loans || []).find(
      (l: any) => l?.status === "active"
    );
    const weeksPaid =
      activeLoan?.weeksPaid ?? m?.collection?.numberOfPayments ?? 0;
    return Number(weeksPaid) || 0;
  };

  // Title rows
  sheetData.push(["DYNAMIC CREDIT AND LOAN SOLUTIONS (DCLA)"]);
  sheetData.push(["GROUP COLLECTION REPORT"]);
  sheetData.push([""]);

  // Center info block
  sheetData.push([
    "Center Name",
    collectionGroup.centerName,
    "",
    "",
    "Collection Day",
    collectionGroup.collectionDay,
    "",
    "",
    "Collection Date",
    collectionGroup.collectionDate,
  ]);
  sheetData.push(["Number of Clients", collectionGroup.totalMembers]);
  sheetData.push([""]);

  // Daily collection table header (short labels to keep sheet narrow)
  sheetData.push([
    "Client",
    "Contact",
    "Loan",
    "Overall",
    "Term",
    "Due",
    "Received",
    "Net Rel.",
    "Payments",
    "Savings",
    "Remain",
    "Status",
  ]);

  // Daily collection table rows
  members.forEach((member) => {
    const received = getMemberReceived(member as any);
    const weeksPaid = getMemberWeeksPaid(member as any);
    const netRelease =
      (member as any)?.collection?.netRelease ??
      (member as any)?.netCashReleased ??
      0;
    sheetData.push([
      `${member.firstName} ${member.middleName || ""} ${member.lastName}`,
      `${member.contactNumber ? "\n" + member.contactNumber : ""}`,
      `₱${member.totalLoanAmount?.toLocaleString() || "0"}`,
      `₱${member.overallAmount?.toLocaleString() || "0"}`,
      member.totalTermWeeks || "0",
      `₱${member.weeklyPaymentAmount?.toLocaleString() || "0"}`,
      `₱${(Number(received) || 0).toLocaleString()}`,
      `₱${(Number(netRelease) || 0).toLocaleString()}`,
      weeksPaid || "0",
      `₱${member.totalSavings?.toLocaleString() || "0"}`,
      `₱${member.totalBalance?.toLocaleString() || "0"}`,
      (Number(received) || 0) >= (member.weeklyPaymentAmount || 0)
        ? "PAID"
        : (Number(received) || 0) > 0
        ? "PARTIAL"
        : "UNPAID",
    ]);
  });

  sheetData.push([""]);

  // Financial summary block
  const totalLoanAmount = members.reduce(
    (sum, m) => sum + (m.totalLoanAmount || 0),
    0
  );
  const totalOverallAmount = members.reduce(
    (sum, m) => sum + (m.overallAmount || 0),
    0
  );
  const totalWeeklyPayments = members.reduce(
    (sum, m) => sum + (m.weeklyPaymentAmount || 0),
    0
  );
  const totalNetCashReleased = members.reduce(
    (sum, m) => sum + (m.netCashReleased || 0),
    0
  );
  const totalSavings = members.reduce(
    (sum, m) => sum + (m.totalSavings || 0),
    0
  );
  const totalRemainingBalance = members.reduce(
    (sum, m) => sum + (m.totalBalance || 0),
    0
  );
  const paidMembers = members.filter((m: any) => {
    const received = getMemberReceived(m);
    return received >= Number(m.weeklyPaymentAmount || 0);
  }).length;
  const partialMembers = members.filter((m: any) => {
    const received = getMemberReceived(m);
    const weekly = Number(m.weeklyPaymentAmount || 0);
    return received > 0 && received < weekly;
  }).length;
  const unpaidMembers = members.filter((m: any) => {
    const received = getMemberReceived(m);
    return !m.collection || received <= 0;
  }).length;

  sheetData.push(["Financial Summary"]);
  sheetData.push([""]);
  sheetData.push(["Total Loan Amount", `₱${totalLoanAmount.toLocaleString()}`]);
  sheetData.push([
    "Total Overall Amount",
    `₱${totalOverallAmount.toLocaleString()}`,
  ]);
  sheetData.push([
    "Total Weekly Payments",
    `₱${totalWeeklyPayments.toLocaleString()}`,
  ]);
  const totalPaymentReceived = members.reduce(
    (sum, m) => sum + getMemberReceived(m as any),
    0
  );
  sheetData.push([
    "Total Payment Received",
    `₱${totalPaymentReceived.toLocaleString()}`,
  ]);
  sheetData.push([
    "Total Net Cash Released",
    `₱${totalNetCashReleased.toLocaleString()}`,
  ]);
  sheetData.push(["Total Savings", `₱${totalSavings.toLocaleString()}`]);
  sheetData.push([
    "Total Remaining Balance",
    `₱${totalRemainingBalance.toLocaleString()}`,
  ]);
  sheetData.push([""]);
  sheetData.push(["Payment Status Summary"]);
  sheetData.push(["Paid Members", paidMembers]);
  sheetData.push(["Partial Payment Members", partialMembers]);
  sheetData.push(["Unpaid Members", unpaidMembers]);

  // Merge title rows across first 12 columns (A..L)
  const merges = [
    { s: { r: 0, c: 0 }, e: { r: 0, c: 11 } },
    { s: { r: 1, c: 0 }, e: { r: 1, c: 11 } },
  ];

  return { data: sheetData, merges };
};

// Helper: create worksheet with light styling
const buildWorksheet = async (
  data: (string | number)[][],
  merges: { s: { r: number; c: number }; e: { r: number; c: number } }[],
  sheetName: string
) => {
  const XLSX = await import("xlsx");
  const ws = XLSX.utils.aoa_to_sheet(data);
  (ws as any)["!merges"] = merges;

  // Narrower columns: clamp widths more aggressively to keep sheet compact
  const maxCols = data.reduce((max, r) => Math.max(max, r.length), 0);
  const maxColWidths = new Array(maxCols).fill(8);
  data.forEach((row) => {
    row.forEach((cell, idx) => {
      const len = String(cell ?? "").length;
      // Add small padding, clamp to 28 characters max to reduce width
      maxColWidths[idx] = Math.min(
        Math.max(maxColWidths[idx], Math.min(len + 1, 28)),
        28
      );
    });
  });
  (ws as any)["!cols"] = maxColWidths.map((w) => ({ width: w }));

  // Attempt light styling (header bold). Note: Some libraries may ignore styles on write.
  const headerRowIndex = data.findIndex((r) => r[0] === "Client Name");
  if (headerRowIndex >= 0) {
    const headerRow = data[headerRowIndex];
    for (let c = 0; c < headerRow.length; c += 1) {
      const cellRef = XLSX.utils.encode_cell({ r: headerRowIndex, c });
      const cell = (ws as any)[cellRef] || {};
      (cell as any).s = { font: { bold: true } };
      (ws as any)[cellRef] = cell;
    }
  }

  // Bold main titles
  [0, 1].forEach((r) => {
    const row = data[r] || [];
    for (let c = 0; c < (row.length || 1); c += 1) {
      const cellRef = XLSX.utils.encode_cell({ r, c });
      const cell = (ws as any)[cellRef] || {};
      (cell as any).s = { font: { bold: true } };
      (ws as any)[cellRef] = cell;
    }
  });

  return { ws, sheetName };
};

export const exportToExcel = async (
  collectionGroup: DailyCollectionGroup,
  members: MemberWithLoans[]
): Promise<void> => {
  try {
    const XLSX = await import("xlsx");
    const FileSaver = await import("file-saver");

    const { data, merges } = buildGroupSheetData(collectionGroup, members);
    const { ws } = await buildWorksheet(data, merges, "Group Report");

    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, ws, "Group Report");

    const fileName = `Collection_Report_${
      collectionGroup.centerName
    }_${collectionGroup.collectionDate.replace(/-/g, "_")}.xlsx`;

    const excelBuffer = XLSX.write(workbook, {
      bookType: "xlsx",
      type: "array",
    });
    const blob = new Blob([excelBuffer], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    });
    FileSaver.saveAs(blob, fileName);
  } catch (error) {
    console.warn("XLSX export failed, falling back to CSV:", error);
    exportToCSV(collectionGroup, members);
  }
};

// New: Export all collections for the day (multiple sheets, one per collection)
export const exportAllCollectionsToExcel = async (
  bundles: CollectionExportBundle[],
  fileNamePrefix = "Daily_Collections"
): Promise<void> => {
  if (!bundles || bundles.length === 0) return;
  const XLSX = await import("xlsx");
  const FileSaver = await import("file-saver");

  const workbook = XLSX.utils.book_new();

  // Build Summary sheet: aggregates across all groups for the day
  try {
    const totalReceived = bundles.reduce(
      (sum, b) =>
        sum +
        (b.group.collections || []).reduce(
          (s, c: any) =>
            s + (Number(c.paymentReceived ?? c.amountReceived) || 0),
          0
        ),
      0
    );
    const totalRemaining = bundles.reduce((sum, b) => {
      const members = b.members || [];
      const totalBalance = members.reduce(
        (s, m: any) => s + (Number(m.totalBalance) || 0),
        0
      );
      const received = (b.group.collections || []).reduce(
        (s, c: any) => s + (Number(c.paymentReceived ?? c.amountReceived) || 0),
        0
      );
      return sum + Math.max(0, totalBalance - received);
    }, 0);
    const totalReleased = bundles.reduce(
      (sum, b) =>
        sum +
        (b.members || []).reduce(
          (s, m: any) => s + (Number(m.netCashReleased) || 0),
          0
        ),
      0
    );
    const date = bundles[0]?.group.collectionDate || "";

    const summaryData: (string | number)[][] = [];
    summaryData.push(["DYNAMIC CREDIT AND LOAN SOLUTIONS (DCLA)"]); // title
    summaryData.push(["END-OF-DAY COLLECTION SUMMARY"]);
    summaryData.push([""]);
    summaryData.push(["Date", date]);
    summaryData.push([""]);
    summaryData.push(["Total Collected", `₱${totalReceived.toLocaleString()}`]);
    summaryData.push([
      "Unpaid (Remaining)",
      `₱${totalRemaining.toLocaleString()}`,
    ]);
    summaryData.push(["Released", `₱${totalReleased.toLocaleString()}`]);
    summaryData.push([""]);
    summaryData.push(["Breakdown by Center"]);
    summaryData.push(["Center", "Collected", "Unpaid", "Released"]);
    for (const { group, members } of bundles) {
      const collected = (group.collections || []).reduce(
        (s, c: any) => s + (Number(c.paymentReceived ?? c.amountReceived) || 0),
        0
      );
      const rem = Math.max(
        0,
        (members || []).reduce(
          (s, m: any) => s + (Number(m.totalBalance) || 0),
          0
        ) - collected
      );
      const released = (members || []).reduce(
        (s, m: any) => s + (Number(m.netCashReleased) || 0),
        0
      );
      summaryData.push([
        group.centerName,
        `₱${collected.toLocaleString()}`,
        `₱${rem.toLocaleString()}`,
        `₱${released.toLocaleString()}`,
      ]);
    }

    const { ws: summaryWs } = await (async () => {
      const ws = XLSX.utils.aoa_to_sheet(summaryData);
      (ws as any)["!merges"] = [
        { s: { r: 0, c: 0 }, e: { r: 0, c: 3 } },
        { s: { r: 1, c: 0 }, e: { r: 1, c: 3 } },
      ];
      const maxCols = summaryData.reduce((m, r) => Math.max(m, r.length), 0);
      (ws as any)["!cols"] = new Array(maxCols)
        .fill(0)
        .map((_, i) => ({ width: 22 }));
      return { ws };
    })();
    XLSX.utils.book_append_sheet(workbook, summaryWs, "Summary");
  } catch (e) {
    console.warn("Failed to build Summary sheet", e);
  }

  for (const { group, members } of bundles) {
    const { data, merges } = buildGroupSheetData(group, members);
    // Build per-center unpaid section to append to data before creating worksheet
    const getMemberReceived = (m: any): number => {
      const fromCollection =
        m?.collection?.amountReceived ?? m?.collection?.paymentReceived;
      if (fromCollection !== undefined) return Number(fromCollection) || 0;
      const activeLoan = (m?.loans || []).find(
        (l: any) => l?.status === "active"
      );
      const amountPaidRaw = activeLoan?.amountPaid;
      if (amountPaidRaw !== undefined) return Number(amountPaidRaw) || 0;
      const weeksPaid = Number(activeLoan?.weeksPaid || 0);
      const weekly = Number(
        m?.weeklyPaymentAmount || activeLoan?.weeklyPaymentAmount || 0
      );
      return weeksPaid * weekly;
    };
    const unpaidMembers = (members || []).filter(
      (m: any) => (getMemberReceived(m) || 0) <= 0
    );
    const unpaidTodayTotal = unpaidMembers.reduce(
      (s: number, m: any) => s + Number(m.weeklyPaymentAmount || 0),
      0
    );
    const unpaidBalancesTotal = unpaidMembers.reduce(
      (s: number, m: any) => s + Number(m.totalBalance || 0),
      0
    );

    data.push([""]); // spacer
    data.push(["Unpaid Members (Today)"]); // section title
    data.push(["Name", "Weekly Due", "Remaining Bal."]);
    unpaidMembers.forEach((m: any) => {
      data.push([
        `${m.firstName} ${m.middleName || ""} ${m.lastName}`.trim(),
        `₱${(Number(m.weeklyPaymentAmount) || 0).toLocaleString()}`,
        `₱${(Number(m.totalBalance) || 0).toLocaleString()}`,
      ]);
    });
    data.push([
      "Totals",
      `₱${unpaidTodayTotal.toLocaleString()}`,
      `₱${unpaidBalancesTotal.toLocaleString()}`,
    ]);
    const sheetTitleBase = `${group.centerName}`.trim();
    const sheetName = sheetTitleBase.substring(0, 31) || "Collection"; // Excel limit
    const { ws } = await buildWorksheet(data, merges, sheetName);
    XLSX.utils.book_append_sheet(workbook, ws, sheetName);
  }

  const firstDate = bundles[0]?.group.collectionDate?.replace(/-/g, "_") || "";
  const fileName = `${fileNamePrefix}_${firstDate}.xlsx`;

  const excelBuffer = XLSX.write(workbook, { bookType: "xlsx", type: "array" });
  const blob = new Blob([excelBuffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  FileSaver.saveAs(blob, fileName);
};
